In [1]:
import numpy as np

In [29]:
a = np.array([[-1,2,3],[5,-6,7],[9,1,0]])
b = np.array([[0,9,1],[-5,3,1],[6,3,9]])

In [32]:
a

array([[-1,  2,  3],
       [ 5, -6,  7],
       [ 9,  1,  0]])

In [33]:
b

array([[ 0,  9,  1],
       [-5,  3,  1],
       [ 6,  3,  9]])

In [11]:
np.absolute(a)

array([[1, 2, 3],
       [5, 6, 7],
       [9, 1, 0]])

In [12]:
np.absolute(b)

array([[0, 9, 1],
       [5, 3, 1],
       [6, 3, 9]])

In [13]:
np.negative(a)

array([[ 1, -2, -3],
       [-5,  6, -7],
       [-9, -1,  0]])

In [74]:
np.negative(b)

array([[ 0, -9, -1],
       [ 5, -3, -1],
       [-6, -3, -9]])

In [69]:
np.append(a,[[1,1,1]], axis = 0)

array([[-1,  2,  3],
       [ 5, -6,  7],
       [ 9,  1,  0],
       [ 1,  1,  1]])

In [70]:
np.append(a,[[1],[1],[1]],axis = 1)

array([[-1,  2,  3,  1],
       [ 5, -6,  7,  1],
       [ 9,  1,  0,  1]])

In [72]:
np.delete(a,1,0)

array([[-1,  2,  3],
       [ 9,  1,  0]])

In [73]:
np.delete(a,1,1)

array([[-1,  3],
       [ 5,  7],
       [ 9,  0]])

In [78]:
c = np.concatenate([a,b],axis = 0)
c

array([[-1,  2,  3],
       [ 5, -6,  7],
       [ 9,  1,  0],
       [ 0,  9,  1],
       [-5,  3,  1],
       [ 6,  3,  9]])

In [79]:
d = np.concatenate([a,b],axis = 1)
d

array([[-1,  2,  3,  0,  9,  1],
       [ 5, -6,  7, -5,  3,  1],
       [ 9,  1,  0,  6,  3,  9]])

In [82]:
d[2,:]

array([9, 1, 0, 6, 3, 9])

In [83]:
c[:,1]

array([ 2, -6,  1,  9,  3,  3])

In [80]:
d[0:2,0:2]

array([[-1,  2],
       [ 5, -6]])

In [84]:
np.max(a)

9

In [98]:
np.max(c,axis=0)

array([9, 9, 9])

In [97]:
np.min(c,axis=0)

array([-5, -6,  0])

In [99]:
np.min(c,axis=1)

array([-1, -6,  0,  0, -5,  3])

In [46]:
for i in range(a.shape[0]):
    print(np.max(a[i,:]))

3
7
9


In [48]:
for i in range(a.shape[0]):
    print(np.min(a[i,:]))

-1
-6
0


In [50]:
for i in range(a.shape[1]):
    print(np.max(a[:,i]))

9
2
7


In [51]:
for i in range(a.shape[1]):
    print(np.min(a[:,i]))

-1
-6
0


In [38]:
np.sum(a)

20