In [269]:
import numpy as np

# Vectors

In [270]:
a = np.random.randint(10, size=[3,1])
a

array([[6],
       [7],
       [5]])

In [271]:
b = np.random.randint(10, size=[1,3])
b

array([[9, 5, 1]])

In [272]:
a+b

array([[15, 11,  7],
       [16, 12,  8],
       [14, 10,  6]])

In [273]:
np.add(a,b)

array([[15, 11,  7],
       [16, 12,  8],
       [14, 10,  6]])

In [274]:
a-b

array([[-3,  1,  5],
       [-2,  2,  6],
       [-4,  0,  4]])

In [275]:
np.subtract(a,b)

array([[-3,  1,  5],
       [-2,  2,  6],
       [-4,  0,  4]])

In [276]:
a*b    #broadcasting of matrices before arithmetic operation

array([[54, 30,  6],
       [63, 35,  7],
       [45, 25,  5]])

In [277]:
np.multiply(a,b)

array([[54, 30,  6],
       [63, 35,  7],
       [45, 25,  5]])

In [278]:
a@b

array([[54, 30,  6],
       [63, 35,  7],
       [45, 25,  5]])

In [291]:
np.matmul(a,b)

array([[54, 30,  6],
       [63, 35,  7],
       [45, 25,  5]])

In [292]:
a[1]

array([7])

In [295]:
a[0:2]

array([[6],
       [7]])

In [296]:
a[:]

array([[6],
       [7],
       [5]])

# Matrices

In [280]:
p = np.random.randint(10, size = [3,3])
p

array([[6, 3, 1],
       [6, 9, 1],
       [5, 1, 6]])

In [281]:
q = np.random.randint(10, size = [3,3])
q

array([[3, 4, 7],
       [6, 0, 3],
       [6, 6, 3]])

In [282]:
p+q

array([[ 9,  7,  8],
       [12,  9,  4],
       [11,  7,  9]])

In [283]:
np.add(p,q)

array([[ 9,  7,  8],
       [12,  9,  4],
       [11,  7,  9]])

In [284]:
p-q

array([[ 3, -1, -6],
       [ 0,  9, -2],
       [-1, -5,  3]])

In [285]:
np.subtract(p,q)

array([[ 3, -1, -6],
       [ 0,  9, -2],
       [-1, -5,  3]])

In [286]:
p*q

array([[18, 12,  7],
       [36,  0,  3],
       [30,  6, 18]])

In [287]:
np.multiply(p,q)

array([[18, 12,  7],
       [36,  0,  3],
       [30,  6, 18]])

In [288]:
p@q

array([[42, 30, 54],
       [78, 30, 72],
       [57, 56, 56]])

In [289]:
np.matmul(p,q)

array([[42, 30, 54],
       [78, 30, 72],
       [57, 56, 56]])

In [301]:
p[2]

array([5, 1, 6])

In [306]:
p[0:2]

array([[6, 3, 1],
       [6, 9, 1]])

In [316]:
p

array([[6, 3, 1],
       [6, 9, 1],
       [5, 1, 6]])

In [321]:
p[1:3,1:3]

array([[9, 1],
       [1, 6]])

In [340]:
np.concatenate([p,q],)

array([[6, 3, 1],
       [6, 9, 1],
       [5, 1, 6],
       [3, 4, 7],
       [6, 0, 3],
       [6, 6, 3]])

In [337]:
np.concatenate([p,q],axis=1)

array([[6, 3, 1, 3, 4, 7],
       [6, 9, 1, 6, 0, 3],
       [5, 1, 6, 6, 6, 3]])